[theme]
base                     = "light"
primaryColor             = "#1D4ED8"
backgroundColor          = "#F8FAFC"
secondaryBackgroundColor = "#EFF6FF"
textColor                = "#0F172A"
font                     = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
