[theme]
base                     = "dark"
primaryColor             = "#3B82F6"
backgroundColor          = "#080C18"
secondaryBackgroundColor = "#0C1424"
textColor                = "#CBD5E1"
font                     = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
